default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: grabbing_dev
test:
  <<: *default
  database: grabbing_test
production:
  <<: *default
  database: grabbing_production
